apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-clone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Metaspolit01/devops-Netflix-clone.git
    targetRevision: main
    path: k8
  destination:
    server: https://kubernetes.default.svc
    namespace: netflix
  syncPolicy:
    syncOptions:
      - CreateNamespace=true   # auto-create namespace if not exists
    automated: {}              # change to {} for auto-sync or remove for manual
